version: "3.8"

services:
  app:
    container_name: boletos-speed-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3030:3030"
    command: npm run dev
    environment:
      - NODE_ENV=development